/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CamvIcon {
        "classNames": string;
        "elementId"?: string;
        "icon": string;
    }
    interface CamvLabel {
        "classNames": string;
        "elementId"?: string;
        "htmlFor"?: string;
        "text": string;
    }
}
declare global {
    interface HTMLCamvIconElement extends Components.CamvIcon, HTMLStencilElement {
    }
    var HTMLCamvIconElement: {
        prototype: HTMLCamvIconElement;
        new (): HTMLCamvIconElement;
    };
    interface HTMLCamvLabelElement extends Components.CamvLabel, HTMLStencilElement {
    }
    var HTMLCamvLabelElement: {
        prototype: HTMLCamvLabelElement;
        new (): HTMLCamvLabelElement;
    };
    interface HTMLElementTagNameMap {
        "camv-icon": HTMLCamvIconElement;
        "camv-label": HTMLCamvLabelElement;
    }
}
declare namespace LocalJSX {
    interface CamvIcon {
        "classNames"?: string;
        "elementId"?: string;
        "icon"?: string;
    }
    interface CamvLabel {
        "classNames"?: string;
        "elementId"?: string;
        "htmlFor"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "camv-icon": CamvIcon;
        "camv-label": CamvLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "camv-icon": LocalJSX.CamvIcon & JSXBase.HTMLAttributes<HTMLCamvIconElement>;
            "camv-label": LocalJSX.CamvLabel & JSXBase.HTMLAttributes<HTMLCamvLabelElement>;
        }
    }
}
